spring.application.name=rdb-study

# 1. DB 연결 주소 (localhost의 3307 포트, rdb_study 데이터베이스)
spring.datasource.url=jdbc:mysql://localhost:3307/rdb_study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

# 2. DB 접속 계정 및 비밀번호
spring.datasource.username=root
spring.datasource.password=test1234

# 3. MySQL 드라이버 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver